### PR TITLE
Splitjaw Spawn Adjustment

### PR DESCRIPTION
**Pull request by Katsuwi**
Increases priority of splitjaw spawns in l2-l3 & make spawns not too far apart to notice. HOPEFULLY without breaking the Mobz.
I miss seeing those guys, the texture work on them is amazing can we see more of them plz?

### CODE REVIEW

**Comment by Boy0000** [comment]
Radius does not matter right now, it is "hardcoded" to 200.
Priority wont affect it much as it is inherent issues with spawning system moreso at this point.

**Comment by Katsuwi** [comment]
I think it would, considering its initial priority is 0.05, about 1/6 the priority for rest of the birds. As seen on l2, majority of the spawns belong to the birds making the splitjaws that do spawn extremely rare

**Comment by Boy0000** [comment]
Majority, like 95% of the mobspawns are passive mobs
Flying spawn abit, but hostiles barely. It is for the most part an inherent issue with mobzy spawning for some reason

**Comment by Katsuwi** [comment]
Yeah, that 5% get distributed between a birds and the majestic splitjaw, sadly splitjaw's on the short end of the stick and doesn't seem to get as much priority as the other birds. With my proposed changes at least some of the birds should be splitjaws right? They're kinda rare as of now

**Comment by c-sig** [comment]
i dont think changing configs would just fix the lack of splitjaws as priority is more like a placebo right now

**Comment by Katsuwi** [comment]
It's not going to fix the mobz spawn issues surely, but I've been down in l2 and I can tell the splitjaw priority is not on par with rest of the birds. It's at least worth a shot and I think it should make a noticeable difference.

**Comment by Boy0000** [comment]
They are meant to be rarer. The reason they are spawning less is due to mobzy spawn system rn
It affects everything but passive mobs, when fixed it will be fixed

**Pull request closed without merging**
