### PR TITLE
Add Calcite to L3

### PR DESCRIPTION
**Pull request by TNTtwins**

### CODE REVIEW

**Comment by TNTtwins** [comment]
Tell me if I need to initialize some sort of calcite class. I will do that. I want to make ground mobs exist in L3.

**Comment by VaIienta** [comment]
We are not going to add calcite to L3 as a block that can be mined for ores, it was originally however calcite is insta mine at like diamond almost so it would create too much of a grind. I know because it is why I removed it.

**Comment by TNTtwins** [comment]
alright. Makes sense. I'll just make mobs spawn on calcite.

**Comment by TNTtwins** [comment]
There, now it's not a material, just a valid transform. I think this is reasonable; L3 is majority calcite, so it being a dud block is an issue for mining. I considered restricting out diamond tools, but that seems like just a waste of time - most people will use diamond tools without knowing the specifics. I will continue to look into ways to make calcite viable in this regard.

**Comment by Boy0000** [comment]
there is an equal amount of calcite white concrete and diorite.
I dont think giving l3 mobs another block to spawn on really adds anything.
If anything it means they will take up more of the mobcap and less variety will be a thing

**Comment by TNTtwins** [comment]
White concrete makes up 1/12 of the blocks. Diorite accounts for another 44.2%, and calcite the remaining 47.4%, more or less.
This, along with the fact that many of the large caves in L3 are made of materials other than diorite and white concrete (grass blocks, stripped nether wood, nylium, obsidian, etc.) means that the ground mobs - rinsipede, virinsipede, kakatsumuri, and neritantan - can really only spawn in the tunnels. That lack of space is why I see the ground mob spawning in L3 as an issue.

**Pull request closed without merging**
