### PR TITLE
Update splitjaw.yml

### PR DESCRIPTION
**Pull request by ShrewdBondrewd**

### CODE REVIEW

**Review by Boy0000 — CHANGES_REQUESTED** [review]
a 3x increase wont be done no...

**Comment by ShrewdBondrewd** [comment]
2x?

**Comment by ShrewdBondrewd** [comment]
I just want to be able to get one in less than 5 hours

**Comment by Boy0000** [comment]
Shulkers will be backpacks eventually. Recipe will change, no clue to what yet. So it will stay the same for now

**Comment by ShrewdBondrewd** [comment]
Oh that works thanks

**Pull request closed without merging**
