### PR TITLE
added PreventRiding component to NPCs

### PR DESCRIPTION
**Pull request by pixelfac**
Dependant on the PreventRiding component from https://github.com/MineInAbyss/Mobzy/pull/37

### CODE REVIEW

**Comment by 0ffz** [comment]
Ohh sorry I thought this PR was for Mobzy as well. Ignore my comment on the other PR then. Just add these components within code in the NPC class. Also when adding an empty component you sadly need to do:
```yaml
- !<component> {}
```

**Comment by 0ffz** [comment]
Alright, this will do for now, I will merge this in once we update Mobzy on the server since we'd get errors for an unknown component otherwise.

**Comment by pixelfac** [comment]
I am learning how github works. I think I have it figured out now. Don't mind all the Reverts

**Comment by 0ffz** [comment]
Implicitly merged, older commit from this branch was used.

**Pull request closed without merging**
